"""add fields  in launched

Revision ID: 0791d2ff7937
Revises: 710804c9e445
Create Date: 2026-06-30 23:18:52.599120

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0791d2ff7937"
down_revision: Union[str, Sequence[str], None] = "710804c9e445"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("grid_launches", sa.Column("stop_loss", sa.Float(), nullable=True))
    op.add_column("grid_launches", sa.Column("take_profit", sa.Float(), nullable=True))
    op.add_column("grid_launches", sa.Column("external_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("grid_launches", "external_id")
    op.drop_column("grid_launches", "take_profit")
    op.drop_column("grid_launches", "stop_loss")
    # ### end Alembic commands ###
