"""init migrations

Revision ID: ddf39e47226d
Revises:
Create Date: 2026-06-21 17:17:44.363724

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ddf39e47226d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision_logs",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("gates_json", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("oid", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("oid"),
    )
    op.create_table(
        "oi_snapshots",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("open_interests", sa.Float(), nullable=False),
        sa.Column("oid", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("oid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oi_snapshots")
    op.drop_table("decision_logs")
    # ### end Alembic commands ###
