"""create new table for launched bot

Revision ID: 710804c9e445
Revises: af452be066a6
Create Date: 2026-06-27 21:22:28.640126

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "710804c9e445"
down_revision: Union[str, Sequence[str], None] = "af452be066a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grid_launches",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("grid_top", sa.Float(), nullable=False),
        sa.Column("grid_bottom", sa.Float(), nullable=False),
        sa.Column("grid_levels", sa.Integer(), nullable=False),
        sa.Column("grid_regime", sa.String(length=16), nullable=False),
        sa.Column("grid_type", sa.String(length=16), nullable=False),
        sa.Column("grid_leverage", sa.Integer(), nullable=False),
        sa.Column("quote_investment", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("realized_pnl", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("decision_verdict_oid", sa.String(length=36), nullable=False),
        sa.Column("oid", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(closed_at IS NULL AND status IN ('running', 'paused')) OR (closed_at IS NOT NULL AND status IN ('closed', 'liquidated'))",
            name="ck_grid_launches_status_closed_at_consistency",
        ),
        sa.CheckConstraint("grid_regime IN ('long', 'short', 'no_trend')", name="chk_regime"),
        sa.CheckConstraint("grid_type IN ('arithmetic', 'geometric')", name="chk_type"),
        sa.CheckConstraint("status IN ('running', 'paused', 'closed', 'liquidated')", name="chk_status"),
        sa.CheckConstraint("grid_levels >= 2 AND grid_levels <= 500", name="ck_grid_launches_levels_platform_range"),
        sa.CheckConstraint("grid_leverage >= 1", name="ck_grid_launches_leverage_positive"),
        sa.CheckConstraint("grid_top > grid_bottom", name="ck_grid_launches_top_gt_bottom"),
        sa.ForeignKeyConstraint(
            ["decision_verdict_oid"],
            ["decision_logs.oid"],
        ),
        sa.PrimaryKeyConstraint("oid"),
    )
    op.create_index(
        op.f("ix_grid_launches_decision_verdict_oid"), "grid_launches", ["decision_verdict_oid"], unique=False
    )
    op.create_index(op.f("ix_grid_launches_symbol"), "grid_launches", ["symbol"], unique=False)
    op.create_index(
        "ux_grid_launches_open_per_symbol",
        "grid_launches",
        ["symbol"],
        unique=True,
        sqlite_where=sa.text("status IN ('running', 'paused')"),
    )
    op.create_index(op.f("ix_decision_logs_symbol"), "decision_logs", ["symbol"], unique=False)
    op.create_index(op.f("ix_oi_snapshots_symbol"), "oi_snapshots", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_oi_snapshots_symbol"), table_name="oi_snapshots")
    op.drop_index(op.f("ix_decision_logs_symbol"), table_name="decision_logs")
    op.drop_index(
        "ux_grid_launches_open_per_symbol",
        table_name="grid_launches",
        sqlite_where=sa.text("status IN ('running', 'paused')"),
    )
    op.drop_index(op.f("ix_grid_launches_symbol"), table_name="grid_launches")
    op.drop_index(op.f("ix_grid_launches_decision_verdict_oid"), table_name="grid_launches")
    op.drop_table("grid_launches")
    # ### end Alembic commands ###
