"""initial_postgresql_schema

Revision ID: ee11aadbec68
Revises:
Create Date: 2026-07-03 21:19:08.943741

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ee11aadbec68"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision_logs",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("gates_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("oid", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("action IN ('launch', 'hold', 'review')", name="chk_action"),
        sa.PrimaryKeyConstraint("oid"),
    )
    op.create_index(op.f("ix_decision_logs_symbol"), "decision_logs", ["symbol"], unique=False)
    op.create_table(
        "oi_snapshots",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("funding_rate_last", sa.Float(), nullable=False),
        sa.Column("funding_rate_annualized_pct", sa.Float(), nullable=False),
        sa.Column("open_interest", sa.Float(), nullable=False),
        sa.Column("oi_pct_change_7d", sa.Float(), nullable=True),
        sa.Column("oid", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("oid"),
    )
    op.create_index("idx_oi_snapshot_symbol_created_at", "oi_snapshots", ["symbol", "created_at"], unique=False)
    op.create_index(op.f("ix_oi_snapshots_symbol"), "oi_snapshots", ["symbol"], unique=False)
    op.create_index(
        "uq_oi_snapshot_symbol_date",
        "oi_snapshots",
        ["symbol", sa.literal_column("((created_at AT TIME ZONE 'UTC')::date)")],
        unique=True,
    )
    op.create_table(
        "grid_launches",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("grid_top", sa.Float(), nullable=False),
        sa.Column("grid_bottom", sa.Float(), nullable=False),
        sa.Column("grid_levels", sa.Integer(), nullable=False),
        sa.Column("grid_regime", sa.String(length=16), nullable=False),
        sa.Column("grid_type", sa.String(length=16), nullable=False),
        sa.Column("grid_leverage", sa.Integer(), nullable=False),
        sa.Column("quote_investment", sa.Float(), nullable=False),
        sa.Column("stop_loss", sa.Float(), nullable=True),
        sa.Column("take_profit", sa.Float(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("realized_pnl", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("health_status", sa.String(length=16), nullable=False),
        sa.Column("distance_to_liquidation_pct", sa.Float(), nullable=True),
        sa.Column("grid_fill_ratio", sa.Float(), nullable=True),
        sa.Column("last_price", sa.Float(), nullable=True),
        sa.Column("last_health_check_at", sa.DateTime(), nullable=True),
        sa.Column("auto_adjust_enabled", sa.Boolean(), nullable=False),
        sa.Column("paused_by_monitor", sa.Boolean(), nullable=False),
        sa.Column("decision_verdict_oid", sa.String(length=36), nullable=False),
        sa.Column("oid", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(closed_at IS NULL AND status IN ('running', 'paused')) OR (closed_at IS NOT NULL AND status IN ('closed', 'liquidated'))",
            name="ck_grid_launches_status_closed_at_consistency",
        ),
        sa.CheckConstraint("grid_regime IN ('long', 'short', 'no_trend')", name="chk_regime"),
        sa.CheckConstraint("grid_type IN ('arithmetic', 'geometric')", name="chk_type"),
        sa.CheckConstraint("health_status IN ('green', 'yellow', 'red')", name="chk_grid_launches_health_status"),
        sa.CheckConstraint("status IN ('running', 'paused', 'closed', 'liquidated')", name="chk_status"),
        sa.CheckConstraint("grid_levels >= 2 AND grid_levels <= 500", name="ck_grid_launches_levels_platform_range"),
        sa.CheckConstraint("grid_leverage >= 1", name="ck_grid_launches_leverage_positive"),
        sa.CheckConstraint("grid_top > grid_bottom", name="ck_grid_launches_top_gt_bottom"),
        sa.ForeignKeyConstraint(
            ["decision_verdict_oid"],
            ["decision_logs.oid"],
        ),
        sa.PrimaryKeyConstraint("oid"),
    )
    op.create_index(
        op.f("ix_grid_launches_decision_verdict_oid"), "grid_launches", ["decision_verdict_oid"], unique=False
    )
    op.create_index(op.f("ix_grid_launches_symbol"), "grid_launches", ["symbol"], unique=False)
    op.create_index(
        "ux_grid_launches_open_per_symbol",
        "grid_launches",
        ["symbol"],
        unique=True,
        postgresql_where=sa.text("status IN ('running', 'paused')"),
    )
    op.create_table(
        "health_snapshots",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("adx14", sa.Float(), nullable=False),
        sa.Column("atr14", sa.Float(), nullable=False),
        sa.Column("atr_pct_of_price", sa.Float(), nullable=False),
        sa.Column("rsi14", sa.Float(), nullable=False),
        sa.Column("realized_vol_1d", sa.Float(), nullable=False),
        sa.Column("realized_vol_7d", sa.Float(), nullable=False),
        sa.Column("last_price", sa.Float(), nullable=False),
        sa.Column("unrealized_pnl", sa.Float(), nullable=False),
        sa.Column("unrealized_pnl_pct", sa.Float(), nullable=False),
        sa.Column("grid_fill_ratio", sa.Float(), nullable=False),
        sa.Column("matched_orders", sa.Integer(), nullable=False),
        sa.Column("total_orders", sa.Integer(), nullable=False),
        sa.Column("distance_to_liquidation_pct", sa.Float(), nullable=False),
        sa.Column("liquidation_price", sa.Float(), nullable=True),
        sa.Column("leverage", sa.Integer(), nullable=False),
        sa.Column("funding_rate", sa.Float(), nullable=False),
        sa.Column("funding_rate_annualized_pct", sa.Float(), nullable=False),
        sa.Column("health_status", sa.String(length=16), nullable=False),
        sa.Column("health_score", sa.Float(), nullable=False),
        sa.Column("grid_launch_oid", sa.String(length=36), nullable=False),
        sa.Column("oid", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("health_status IN ('green', 'yellow', 'red')", name="chk_health_status"),
        sa.ForeignKeyConstraint(
            ["grid_launch_oid"],
            ["grid_launches.oid"],
        ),
        sa.PrimaryKeyConstraint("oid"),
    )
    op.create_index("idx_health_snapshot_bot_time", "health_snapshots", ["grid_launch_oid", "created_at"], unique=False)
    op.create_index(op.f("ix_health_snapshots_grid_launch_oid"), "health_snapshots", ["grid_launch_oid"], unique=False)
    op.create_index(op.f("ix_health_snapshots_symbol"), "health_snapshots", ["symbol"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("alert_type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.Column("acknowledged_by", sa.String(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column("health_snapshot_oid", sa.String(length=36), nullable=True),
        sa.Column("grid_launch_oid", sa.String(length=36), nullable=False),
        sa.Column("oid", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "alert_type IN ('status_change', 'liquidation_risk', 'grid_depletion', 'high_funding', 'volatility_spike', 'pnl_drawdown', 'api_error')",
            name="chk_alert_type",
        ),
        sa.ForeignKeyConstraint(
            ["grid_launch_oid"],
            ["grid_launches.oid"],
        ),
        sa.ForeignKeyConstraint(
            ["health_snapshot_oid"],
            ["health_snapshots.oid"],
        ),
        sa.PrimaryKeyConstraint("oid"),
    )
    op.create_index("idx_alert_bot_time", "alerts", ["grid_launch_oid", "created_at"], unique=False)
    op.create_index("idx_alert_symbol_severity", "alerts", ["symbol", "severity"], unique=False)
    op.create_index(op.f("ix_alerts_grid_launch_oid"), "alerts", ["grid_launch_oid"], unique=False)
    op.create_index(op.f("ix_alerts_health_snapshot_oid"), "alerts", ["health_snapshot_oid"], unique=False)
    op.create_index(op.f("ix_alerts_symbol"), "alerts", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alerts_symbol"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_health_snapshot_oid"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_grid_launch_oid"), table_name="alerts")
    op.drop_index("idx_alert_symbol_severity", table_name="alerts")
    op.drop_index("idx_alert_bot_time", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_health_snapshots_symbol"), table_name="health_snapshots")
    op.drop_index(op.f("ix_health_snapshots_grid_launch_oid"), table_name="health_snapshots")
    op.drop_index("idx_health_snapshot_bot_time", table_name="health_snapshots")
    op.drop_table("health_snapshots")
    op.drop_index(
        "ux_grid_launches_open_per_symbol",
        table_name="grid_launches",
        postgresql_where=sa.text("status IN ('running', 'paused')"),
    )
    op.drop_index(op.f("ix_grid_launches_symbol"), table_name="grid_launches")
    op.drop_index(op.f("ix_grid_launches_decision_verdict_oid"), table_name="grid_launches")
    op.drop_table("grid_launches")
    op.drop_index("uq_oi_snapshot_symbol_date", table_name="oi_snapshots")
    op.drop_index(op.f("ix_oi_snapshots_symbol"), table_name="oi_snapshots")
    op.drop_index("idx_oi_snapshot_symbol_created_at", table_name="oi_snapshots")
    op.drop_table("oi_snapshots")
    op.drop_index(op.f("ix_decision_logs_symbol"), table_name="decision_logs")
    op.drop_table("decision_logs")
    # ### end Alembic commands ###
