"""add composite index

Revision ID: 1e86a420479c
Revises: 23324a53cd77
Create Date: 2026-06-22 21:21:17.854925

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e86a420479c"
down_revision: Union[str, Sequence[str], None] = "23324a53cd77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_oi_snapshot_symbol_created_at", "oi_snapshots", ["symbol", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_oi_snapshot_symbol_created_at", table_name="oi_snapshots")
    # ### end Alembic commands ###
